### ISSUE TITLE
Fichier texte intermediaire vide

### ISSUE THREAD

**Issue by BlondinMymy** [twolaw/convertBNP#1]
Bonjour,
J'utilise votre script python pour convertir mes relevés BNP en fichier excel.
Quand je lance le script, les fichiers de sortie excel sont vides, j'ai seulement : 
Date	Opération	Débit	Crédit
J'ai modifié votre script pour voir les fichiers textes intermédiaires et je n'ai rien dedans, seulement 3 symboles en forme de croix avec un cercle au-dessus.
Savez-vous d'où cela peut venir ? Avez-vous réussi à convertir des relevés 2016 ?
Merci d'avance pour votre aide.

**Comment by simonc56** [comment]
Bonjour,
Oui, les feuilles de relevés de BNP ont changé de format depuis quelques
temps et le script ne marche plus correctement.
J'ai quitté la BNP et je le laisse donc à l'abandon.
Si les fichiers texte sont vides, vérifiez que pdftotext.exe fonctionne
correctement.

Le jeu. 22 déc. 2016 à 16:28, BlondinMymy <notifications@github.com> a
écrit :

**Comment by BlondinMymy** [comment]
A priori le problème vient de l'encodage des relevés BNP en pdf car pdftotext fonctionne sur d'autres pdf...
Pourriez-vous mettre un exemple de fichier texte intermédiaire pour que je vois si je peux utiliser la conversion en txt d'un lecteur PDF (Adobe ou Foxit par exemple). Merci

**Comment by simonc56** [comment]
Voici un exemple de relevé datant de 2013 converti en txt avec pdftotext 3.03 :
[lien zerobin](https://zerobin.net/?7ab6a19b44bbf98e#8sEU51apLUdNALP0YOeaUSKnD21mmST5XDAphkoBtqs=)

**Comment by seiferflo** [comment]
Bonjour. Je suis aussi déçu que twolaw ait abandonné le projet même si je comprends les raisons.
Cependant, est-il possible de demander de l'aide pour faire avancer le projet en fork?

@BlondinMymy As-tu réussi à trouver une solution en utilisant la conversion texte? J'ai essayé, mais les lignes de débit et crédits ne sont pas à la suite de l'opération donc tout est en dans le désordre.

**Comment by seiferflo** [comment]
En fait je viens de m'apercevoir que le nouveau site de BNP offre maintenant la possibilité de faire des exports Excel de 3 mois consécutifs mais sur toute l'année donc plus besoin du convertisseur de twolaw... 
Bonne fêtes !

**Comment by BlondinMymy** [comment]
J'ai modifié le script python pour s'adapter au nouveau format. Toutes les opérations bancaires sont placées dans un seul fichier CSV.

Bonne année à vous !
